### ISSUE TITLE
command "python mapToGrid.py  " crash

### ISSUE THREAD

**Issue by fujin678** [facebookresearch/pyrobot#101]
## Steps to reproduce

  1. _____run master node
roslaunch locobot_control main.launch use_arm:=true use_base:=true use_camera:=true  use_vslam:=true  use_rviz:=false

  2. ____ Now run
python mapToGrid.py
  3. _____

## Observed Results
python mapToGrid.py crash:
 
python  ../../../robots/LoCoBot/locobot_navigation/base_navigation/nodes/mapToGrid.py
[ERROR] [1594874326.630057]: Timeout waiting for Inverse Kinematics Service!!
[ERROR] [1594874329.887497]: Timeout waiting for Forward Kinematics Service!!
Traceback (most recent call last):
  File "../../../robots/LoCoBot/locobot_navigation/base_navigation/nodes/mapToGrid.py", line 139, in <module>
    main()
  File "../../../robots/LoCoBot/locobot_navigation/base_navigation/nodes/mapToGrid.py", line 124, in main
    convertor = PcdToOcGrid(0.3, 0.5, -2.5, -2.5, 2.5, 2.5)
  File "../../../robots/LoCoBot/locobot_navigation/base_navigation/nodes/mapToGrid.py", line 26, in __init__
    "locobot", base_config={"build_map": True, "base_planner": "none"}
  File "/home/lab/pyenv_pyrobot_python2/local/lib/python2.7/site-packages/pyrobot/core.py", line 137, in __init__
    self.base = base_class(self.configs, **base_config)
TypeError: __init__() got an unexpected keyword argument 'build_map'

## Expected Results

  * What did you expect to happen?

## Relevant Code

```
// TODO(you): code here to reproduce the problem
```

**Comment by kalyanvasudev** [comment]
Has been address in e3126f007ac18518c2a0f3c004569ad785bb525d
