### ISSUE TITLE
Can't instantiate Locobot when using vslam

### ISSUE THREAD

**Issue by anuragprat1k** [facebookresearch/pyrobot#143]
I am trying to use vslam for navigation for the [locobot assistant in droidlet](https://github.com/facebookresearch/droidlet/tree/main/locobot). I am unable to instantiate the `Robot` class.

## Steps to reproduce

Installed pyrobot using Python 3 setup

  1. `roslaunch locobot_control main.launch use_base:=true use_arm:=true use_camera:=true teleop:=true use_vslam:=true`
  2. `load_pyrobot_env`
  3. Open up a python shell
     * `from pyrobot import Robot`
     * `r = Robot("locobot")`

## Observed Results

```
(pyenv_pyrobot_python3) locobot@locobot:~$ python
Python 3.6.2 (default, Jul 17 2017, 23:14:31) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyrobot import Robot
>>> r = Robot("locobot")
/home/locobot/low_cost_ws/src/pyrobot/robots/LoCoBot/locobot_navigation/orb_slam2_ros/scripts/orb_slam2_ros/pcdlib.py:153: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg_data = yaml.load(f)
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/nav_msgs/msg/_OccupancyGrid.py", line 140, in serialize
    buff.write(struct.pack(pattern, *self.data))
struct.error: required argument is not an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/locobot/pyrobot_catkin_ws/src/ros_comm/clients/rospy/src/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/home/locobot/pyrobot_catkin_ws/src/ros_comm/clients/rospy/src/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/home/locobot/pyrobot_catkin_ws/src/ros_comm/clients/rospy/src/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/nav_msgs/msg/_OccupancyGrid.py", line 141, in serialize
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 334, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 254, in check_type
    raise SerializationError('field %s must be a list or tuple type'%field_name)
genpy.message.SerializationError: field data must be a list or tuple type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/locobot/pyrobot_catkin_ws/src/ros_comm/clients/rospy/src/rospy/timer.py", line 235, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/home/locobot/low_cost_ws/src/pyrobot/robots/LoCoBot/locobot_navigation/orb_slam2_ros/scripts/orb_slam2_ros/vslam.py", line 289, in _callback_occ_pub
    self._pub_occupancy_map()
  File "/home/locobot/low_cost_ws/src/pyrobot/robots/LoCoBot/locobot_navigation/orb_slam2_ros/scripts/orb_slam2_ros/vslam.py", line 286, in _pub_occupancy_map
    self.occ_map_pub.publish(self.occ_map_msg)
  File "/home/locobot/pyrobot_catkin_ws/src/ros_comm/clients/rospy/src/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: field data must be a list or tuple type

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/locobot/pyenv_pyrobot_python3/lib/python3.6/site-packages/pyrobot/core.py", line 144, in __init__
    self.base = base_class(self.configs, **base_config)
  File "/home/locobot/pyenv_pyrobot_python3/lib/python3.6/site-packages/pyrobot/locobot/base.py", line 286, in __init__
    self.load_planner(base_planner)
  File "/home/locobot/pyenv_pyrobot_python3/lib/python3.6/site-packages/pyrobot/locobot/base.py", line 316, in load_planner
    self.planner = MoveBasePlanner(self.configs, self._as)
  File "/home/locobot/pyenv_pyrobot_python3/lib/python3.6/site-packages/pyrobot/locobot/base_control_utils.py", line 248, in __init__
    rospy.wait_for_service(self.configs.BASE.PLAN_TOPIC, timeout=3)
  File "/home/locobot/pyrobot_catkin_ws/src/ros_comm/clients/rospy/src/rospy/impl/tcpros_service.py", line 143, in wait_for_service
    raise ROSException("timeout exceeded while waiting for service %s"%resolved_name)
rospy.exceptions.ROSException: timeout exceeded while waiting for service /move_base/GlobalPlanner/make_plan
```

## Expected Results

  * No exceptions?

## Relevant Code

```
// TODO(you): code here to reproduce the problem
```

**Comment by Jekyll1021** [comment]
Closing the issue since #147 has suggested fix.
