### ISSUE TITLE
pyrobot in habitat

### ISSUE THREAD

**Issue by GuoPingPan** [facebookresearch/pyrobot#212]
Hi，I want to know how to use the `pyrobot_noisy_controls.py` in `habitat-sim`，it need pyrobot，then I just install it by
```
pip install pyrobot
```
and run the code comes the error as below
```
ModuleNotFoundError: No module named 'pyrobot.forms'
```
then I think may be I have not install entire `pyrobot` package, so I decide to down it following this repository, but I actually don't need to run in ros, so I only want to build the python part of the package, so I run below code
```
# my python env is python3
git clone --recurse-submodules https://github.com/facebookresearch/pyrobot.git
cd pyrobot/
pip install .
```
the process had done successfully!
but when I try to import pyrobot, come the error below, I know it is because the tf in ros and conflict with python3
```
>>> import pyrobot.forms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pgp/anaconda3/envs/eai/lib/python3.8/site-packages/pyrobot/__init__.py", line 6, in <module>
    from pyrobot.core import Robot
  File "/home/pgp/anaconda3/envs/eai/lib/python3.8/site-packages/pyrobot/core.py", line 18, in <module>
    import tf
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define module export function (PyInit__tf2)
```
#94 say source the workspace, but I don't want to use ros, if there is any other easy way to install `pyrobot` for `habitat`?

**Comment by GuoPingPan** [comment]
@kalyanvasudev Please help me!
